#!/usr/bin/env python3
"""Regenerate the reference parts of docs/profiles.md and docs/checks.md.

Everything above the marker line in each file is hand-written; everything below
it is generated from the check registry and the built-in profile files, so the
documentation cannot drift from the code. CI runs ``--check``.

    python scripts/gen_docs.py          # rewrite the generated sections
    python scripts/gen_docs.py --check  # exit 1 if they are out of date
"""

from __future__ import annotations

import argparse
import os
import sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
sys.dont_write_bytecode = True  # no __pycache__ (with this machine's paths in it) inside src/
sys.path.insert(0, os.path.join(ROOT, "src"))

from social_video_qa.checks import FIX_STRATEGY, REGISTRY, describe_rule  # noqa: E402
from social_video_qa.profiles import builtin_ids, load_profile  # noqa: E402
from social_video_qa.report import render_profile_markdown  # noqa: E402

MARKER = "<!-- Everything below is generated by scripts/gen_docs.py from the code. Do not edit it by hand. -->"
ORDER = [
    "instagram-reels-api",
    "instagram-story-api",
    "meta-ads-instagram",
    "app-store-preview-iphone",
    "app-store-preview-ipad",
    "youtube-shorts",
    "tiktok",
]

FIX_TEXT = {
    "remux": "yes, without re-encoding (remux)",
    "audio": "yes, re-encodes the audio only",
    "video": "yes, re-encodes the video",
}


def _cell(prof, cid: str) -> str:
    params = prof.rules.get(cid)
    if params is None or params.get("severity") == "off":
        return "-"
    return describe_rule(cid, params).replace("|", "\\|")


def profiles_section() -> str:
    ids = [p for p in ORDER if p in builtin_ids()] + [p for p in builtin_ids() if p not in ORDER]
    out = [
        "## At a glance\n",
        "| Profile | Duration | Frame size | Frame rate | Max file size | Video codec |",
        "| --- | --- | --- | --- | --- | --- |",
    ]
    for pid in ids:
        prof = load_profile(pid)
        size = _cell(prof, "video.size")
        if size == "-":
            size = _cell(prof, "video.aspect")
        cells = [
            _cell(prof, "duration"),
            size,
            _cell(prof, "video.fps"),
            _cell(prof, "file.size"),
            _cell(prof, "video.codec"),
        ]
        out.append(f"| [`{pid}`](#{pid.replace('.', '')}) | " + " | ".join(cells) + " |")
    out.append("")
    for pid in ids:
        prof = load_profile(pid)
        out.append(f"## `{prof.id}`\n")
        out.append(f"**{prof.title}**" + (f", extends `{', '.join(prof.extends)}`" if prof.extends else "") + "\n")
        out.append(prof.description + "\n")
        out.append("Sources:\n")
        for src in prof.sources:
            out.append(f"- [{src['title']}]({src['url']}) (checked {src.get('checked', '?')})")
        out.append("")
        out.append(render_profile_markdown(prof))
        if prof.notes:
            out.append("Notes and uncertainty:\n")
            out.extend(f"- {n}" for n in prof.notes)
            out.append("")
        fix = prof.fix
        if fix:
            v, a = fix.get("video", {}), fix.get("audio", {})
            rate = f"CBR {v['cbr_kbps']} kbps" if v.get("cbr_kbps") else f"CRF {v.get('crf', 20)}"
            if v.get("maxrate_kbps"):
                rate += f", max {v['maxrate_kbps']} kbps"
            level = f" level {v['level']}" if v.get("level") else ""
            out.append(
                f"`svqa fix` target: {fix.get('size', 'source size')}, H.264 {v.get('profile', 'high')}{level}, "
                f"{rate}, AAC {a.get('bitrate_kbps', 128)} kbps {a.get('sample_rate', 48000)} Hz, "
                f"loudness {fix.get('loudness', {}).get('target_lufs', 'off')} LUFS.\n"
            )
    return "\n".join(out).rstrip() + "\n"


def checks_section() -> str:
    out = ["| Check | Default severity | Fixable by `svqa fix` | Parameters |", "| --- | --- | --- | --- |"]
    for cid, cdef in REGISTRY.items():
        params = ", ".join(f"`{name}` ({ptype.label})" for name, ptype in cdef.params.items()) or "none"
        fix = FIX_TEXT.get(FIX_STRATEGY.get(cid, ""), "no")
        if cid == "duration":
            fix = "only too long, with `--trim`"
        out.append(f"| [`{cid}`](#{cid.replace('.', '')}) | {cdef.severity} | {fix} | {params} |")
    out.append("")
    for cid, cdef in REGISTRY.items():
        out.append(f"### `{cid}`\n")
        out.append(f"**{cdef.title}.** {cdef.doc}\n")
        if cdef.needs:
            out.append(f"Needs analysis: {', '.join(sorted(cdef.needs))} (skipped with `--fast`).\n")
        out.append(f"How to fix: {cdef.hint}\n")
    return "\n".join(out).rstrip() + "\n"


def render(path: str, section: str) -> tuple[str, str]:
    with open(path, encoding="utf-8") as f:
        current = f.read()
    head, sep, _old = current.partition(MARKER)
    if not sep:
        raise SystemExit(f"{path}: marker line not found")
    return current, head + MARKER + "\n\n" + section


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("--check", action="store_true", help="fail if the generated sections are out of date")
    args = parser.parse_args()
    stale = []
    for name, section in (("profiles.md", profiles_section()), ("checks.md", checks_section())):
        path = os.path.join(ROOT, "docs", name)
        current, wanted = render(path, section)
        if current != wanted:
            if args.check:
                stale.append(name)
            else:
                with open(path, "w", encoding="utf-8", newline="\n") as f:
                    f.write(wanted)
                print(f"updated docs/{name}")
    if stale:
        print(f"out of date: {', '.join(stale)}; run python scripts/gen_docs.py", file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
